// <auto-generated />
namespace _14_GeneralStoreAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EmptyMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmptyMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202201131916139_EmptyMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
